language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

before_install:
 - chmod +x gradlew
 - chmod +x .travis-scripts/deploy-artifacts.sh
 - chmod +x .travis-scripts/push-javadoc-to-gh-pages.sh

after_success:
 - ./gradlew cobertura coveralls
 - .travis-scripts/deploy-artifacts.sh
 - .travis-scripts/push-javadoc-to-gh-pages.sh
