language: java

jdk:
  - oraclejdk8

before_install:
 - chmod +x gradlew
 - chmod +x .travis-scripts/deploy-artifacts.sh
 - chmod +x .travis-scripts/push-javadoc-to-gh-pages.sh

after_success:
 - ./gradlew jacocoTestReport coveralls
 - .travis-scripts/deploy-artifacts.sh
 - .travis-scripts/push-javadoc-to-gh-pages.sh
 - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
